### ISSUE TITLE
CSS completion should not happen after ';'

### ISSUE THREAD

**Issue by magcius** [auto-complete/auto-complete#56]
``` css
body {
    background-color: white;
}
```

Putting your cursor over the `;` and hitting the `ac-expand` key, it tries to complete for colors. This is quite annoying.
